[package]
name = "w01_signature_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = {  version = "2", features = ["rand_core"]}
rand = { workspace = true }
hex = { workspace = true }
